site_name: '${{values.destination.repo}}'
site_description: 'Main documentation for Backstage features and platform APIs'
repo_url: https://github.com/${{values.destination.owner + "/" + values.destination.repo}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Getting Started:
      - Getting Started: 'docs/index.md'
